version: '3.7'

services:
  fulfillment-public-web-app:
    environment:
      HOST: 0.0.0.0
      PORT: 8080
      VITE_APP_HOST: localhost:8080
    build:
      dockerfile: Dockerfile
      context: .
    restart: unless-stopped
    volumes:
      - ../..:/app
    working_dir: /app
    command: tail -f /dev/null
    ports:
      - "8080:8080"
